/* Generated by tools/gen_puzzles.py from assets/puzzles -- do not edit. */
#ifndef PUZZLES_H
#define PUZZLES_H

#define PUZZLE_COUNT 95
#define GROUP_COUNT 7
#define CELL_GIVEN 0x10

/* Groups of one size and difficulty: grid size, stars, first puzzle, count. */
extern const unsigned char group_n[GROUP_COUNT], group_stars[GROUP_COUNT];
extern const unsigned char group_first[GROUP_COUNT], group_count[GROUP_COUNT];

/* Puzzle k (0-based) starts at puzzle_data + puzzle_offset[k]: n, stars, then
 * n*n cells: 0 black, 1-9 the solution digit, | CELL_GIVEN for a given. */
extern const unsigned int puzzle_offset[PUZZLE_COUNT];
extern const unsigned char puzzle_data[];

#endif
